### ISSUE TITLE
which torchtext version?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Stability-AI/stablediffusion#15]
With torchtext 0.14.0 I got

```
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from pytorch_lightning import seed_everything
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics, void
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/metrics/utils.py", line 29, in <module>
    from pytorch_lightning.utilities import rank_zero_deprecation
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/utilities/apply_func.py", line 31, in <module>
    from torchtext.legacy.data import Batch
ModuleNotFoundError: No module named 'torchtext.legacy'
```

**Comment by woctezuma** [comment]
Related:
- #8

**Comment by 0xdevalias** [comment]
> https://github.com/pytorch/text#installation
> 
> The following are the corresponding `torchtext` versions and supported Python versions.
>
> ..snip..
>
> ---
> 
> Based on that, it looks like you want to be using one of these combinations presumably?
> 
> > PyTorch version | torchtext version | Supported Python version
> > -- | -- | --
> > 1.10.0 | 0.11.0 | >=3.6, <=3.9
> > 1.9.1 | 0.10.1 | >=3.6, <=3.9
> 
> ---
> 
> What version of PyTorch are you using alongside `torchtext` `0.10`? As I suspect that will likely be the source of your `ModuleNotFoundError: No module named 'torch.ao.quantization'` error.
> 
> _Originally posted by @0xdevalias in https://github.com/Stability-AI/stablediffusion/issues/8#issuecomment-1326313884_

---

> - https://github.com/pytorch/pytorch/tree/v1.9.1/torch/ao/quantization
>   - > The `pytorch/pytorch` repository doesn't contain the `torch/ao/quantization` path in `v1.9.1`
> - https://github.com/pytorch/pytorch/tree/v1.10.2/torch/ao/quantization
>   - Path seems to exist in `v1.10.2`
> 
> _Originally posted by @0xdevalias in https://github.com/Stability-AI/stablediffusion/issues/8#issuecomment-1326319525_

**Comment by FrancescoSaverioZuppichini** [comment]
Googling the error (which I did), doesn't fix it just generate another error (correctly shown in the other issue. Closing in favor of the other
