### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by francescapalermo** [Stability-AI/stablediffusion#181]
I get the following error when running the txt2img.py using these arguments:
```
"args": ["--prompt", "a professional photograph of an astronaut riding a horse", 
         "--ckpt", "checkpoints/ema_pruned.ckpt", 
         "--config", "configs/stable-diffusion/v2-inference-v.yaml", 
         "--H", "768",
         "--W", "768", 
        "--precision", "full"]
```
Installation has been performed on Anaconda virtual environment on Windows 11 following the tutorial in the README file. 

```
Exception has occurred: RuntimeError
"slow_conv2d_cpu" not implemented for 'Half'
  File "stablediffusion-main\ldm\modules\diffusionmodules\openaimodel.py", line 86, in forward
    x = layer(x)
  File "stablediffusion-main\ldm\modules\diffusionmodules\openaimodel.py", line 780, in forward
    h = module(h, emb, context)
  File "stablediffusion-main\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "stablediffusion-main\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "stablediffusion-main\ldm\models\diffusion\ddim.py", line 212, in p_sample_ddim
    model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "stablediffusion-main\ldm\models\diffusion\ddim.py", line 164, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "stablediffusion-main\ldm\models\diffusion\ddim.py", line 104, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "stablediffusion-main\scripts\txt2img.py", line 349, in main
    samples, _ = sampler.sample(S=opt.steps,
  File "stablediffusion-main\scripts\txt2img.py", line 390, in <module>
    main(opt)
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
```

**Comment by mehmet-zahid** [comment]
I have also got the same error . I am using google colab gpu and conda envirement .
python /content/stablediffusion/scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt /content/my_model.ckpt --config /content/stablediffusion/configs/stable-diffusion/v2-inference-v.yaml --H 768 --W 768  


Traceback (most recent call last):
  File "/content/stablediffusion/scripts/txt2img.py", line 388, in <module>
    main(opt)
  File "/content/stablediffusion/scripts/txt2img.py", line 347, in main
    samples, _ = sampler.sample(S=opt.steps,
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/stablediffusion/ldm/models/diffusion/ddim.py", line 104, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/stablediffusion/ldm/models/diffusion/ddim.py", line 164, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/stablediffusion/ldm/models/diffusion/ddim.py", line 212, in p_sample_ddim
    model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/content/stablediffusion/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stablediffusion/ldm/models/diffusion/ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 778, in forward
    h = module(h, emb, context)
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/stablediffusion/ldm/modules/diffusionmodules/openaimodel.py", line 86, in forward
    x = layer(x)
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

**Comment by francescapalermo** [comment]
I think this version is not working with Windows because of the xconders library not recognising the GPU. 
I tried the webui version and it works without any errors. You can try installing from [here](https://github.com/cmdr2/stable-diffusion-ui)

**Comment by huanmei9** [comment]
You can try setting the `use_fp16` to _false_ in the YAML configuration file.

**Comment by hitesh-suthar-inferenz** [comment]
Hi, can anyone please tell me in which file I need to change this parameter, I am unable to find this parameters

**Comment by huanmei9** [comment]
@hitesh-suthar-inferenz  try [this](https://github.com/Stability-AI/stablediffusion/blob/cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf/configs/stable-diffusion/v2-inference.yaml#LL24C9-L24C17)
