### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by owenmatrix** [Stability-AI/stablediffusion#200]
This issue bothers me a lot, could anyone help me.
when the process comes to the end, the code below appears:

`Error completing request
Arguments: ('task(k0yw1lchohcyis6)', 'an office lady, suit, professional, ((ultra-detailed)),(detailedlight),(high detailed skin:1.2), dramatic_shadow, ray_tracing,', '(worst quality:2), (low quality:2), lowres,((monochrome)), ((grayscale)), paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, ((monochrome)), ((grayscale)), skin spots, age spot, glans,extra fingers,fewer fingers, (normal quality:2), lowres, ((monochrome)), ((grayscale)),jpeg artifacts, signature, watermark', [], 20, 8, True, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', False, False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 0, 1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, 50) {}
Traceback (most recent call last):
  File "/Users/haowen/stable-diffusion-webui/modules/call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "/Users/haowen/stable-diffusion-webui/modules/call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "/Users/haowen/stable-diffusion-webui/modules/txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "/Users/haowen/stable-diffusion-webui/modules/processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "/Users/haowen/stable-diffusion-webui/modules/processing.py", line 664, in process_images_inner
    x_sample = modules.face_restoration.restore_faces(x_sample)
  File "/Users/haowen/stable-diffusion-webui/modules/face_restoration.py", line 19, in restore_faces
    return face_restorer.restore(np_image)
  File "/Users/haowen/stable-diffusion-webui/modules/codeformer_model.py", line 88, in restore
    self.create_models()
  File "/Users/haowen/stable-diffusion-webui/modules/codeformer_model.py", line 65, in create_models
    checkpoint = torch.load(ckpt_path)['params_ema']
TypeError: 'NoneType' object is not subscriptable
`

**Comment by leninrkb** [comment]
Did you download the weights? looks like you're trying without it. Please give more info to help you.
