### ISSUE TITLE
assert c_adm is not None AssertionError

### ISSUE THREAD

**Issue by aliendaniel** [Stability-AI/stablediffusion#235]
/ldm/models/diffusion/ddpm.py", line 1346, in forward 
   assert c_adm is not None
AssertionError

**Comment by aliendaniel** [comment]
Creating invisible watermark encoder (see https://github.com/ShieldMnt/invisible-watermark)...
Sampling:   0%|                                                                                                                                                                                                                                                                                                                                | 0/3 [00:00<?, ?it/sData shape for DDIM sampling is (3, 4, 96, 96), eta 0.0                                                                                                                                                                                                                                                                                         | 0/1 [00:00<?, ?it/s]
Running DDIM Sampling with 50 timesteps
DDIM Sampler:   0%|                                                                                                                                                                                                                                                                                                                           | 0/50 [00:00<?, ?it/s]
data:   0%|                                                                                                                                                                                                                                                                                                                                    | 0/1 [12:34<?, ?it/s]
Sampling:   0%|                                                                                                                                                                                                                                                                                                                                | 0/3 [12:34<?, ?it/s]
Traceback (most recent call last):
  File "txt2img.py", line 388, in <module>
    main(opt)
  File "txt2img.py", line 347, in main
    samples, _ = sampler.sample(S=opt.steps,
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/xuanwu/Desktop/StableDiffusion/stablediffusion-main/ldm/models/diffusion/ddim.py", line 104, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/xuanwu/Desktop/StableDiffusion/stablediffusion-main/ldm/models/diffusion/ddim.py", line 164, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/xuanwu/Desktop/StableDiffusion/stablediffusion-main/ldm/models/diffusion/ddim.py", line 212, in p_sample_ddim
    model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/Users/xuanwu/Desktop/StableDiffusion/stablediffusion-main/ldm/models/diffusion/ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/xuanwu/Desktop/StableDiffusion/stablediffusion-main/ldm/models/diffusion/ddpm.py", line 1346, in forward
    assert c_adm is not None
AssertionError

**Comment by Jayyyyyyyyyyyy** [comment]
same question

**Comment by gitgotcha77** [comment]
Happens to me too.
My package list:
`  albumentations                 1.3.0         pyhd8ed1ab_0                 conda-forge
  gradio                         3.23.0        pyhd8ed1ab_0                 conda-forge
  kornia                         0.6.11        pyhd8ed1ab_0                 conda-forge
  omegaconf                      2.3.0         pyhd8ed1ab_0                 conda-forge
  open-clip-torch                2.7.0         pyhd8ed1ab_0                 conda-forge
  opencv                         4.7.0         py39hf3d152e_1               conda-forge
  pytorch                        1.13.1        py3.9_cuda11.7_cudnn8.5.0_0  pytorch
  pytorch-cuda                   11.7          h778d358_3                   pytorch
  pytorch-lightning              1.4.9         pyhd8ed1ab_0                 conda-forge
  pytorch-mutex                  1.0           cuda                         pytorch
  sentencepiece                  0.1.96        py39hf939315_1               conda-forge
  torchaudio                     0.13.1        py39_cu117                   pytorch
  torchdata                      0.5.1         py39hebc40ba_1               conda-forge
  torchmetrics                   0.7.3         pyhd8ed1ab_0                 conda-forge
  torchtext                      0.6.0         py_1                         pytorch
  torchvision                    0.14.1        py39_cu117                   pytorch
  tqdm                           4.65.0        pyhd8ed1ab_1                 conda-forge
  transformers                   4.19.4        pyhd8ed1ab_0                 conda-forge
  webdataset                     0.2.48        pyhd8ed1ab_0                 conda-forge
  xformers                       0.0.16        py39h4b4f3f3_2               conda-forge
`

**Comment by fairleehu** [comment]
i have the same question,do you solve it?

**Comment by zzxgdh** [comment]
it doesn't work when using v2-1-stable-unclip-l-inference.yaml, but v2-inference-v.yaml is finished.ckpt is --ckpt models/v2-1_768-ema-pruned.ckpt

**Comment by Morinage** [comment]
> it doesn't work when using v2-1-stable-unclip-l-inference.yaml, but v2-inference-v.yaml is finished.ckpt is --ckpt models/v2-1_768-ema-pruned.ckpt

thankyou！
