### ISSUE TITLE
Binary incompatibility error

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [Stability-AI/stablediffusion#273]
Binary incompatibility error occurred as follows.

```
$ python3 scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt "./768-v-ema.ckpt"  --config configs/stable-diffusion/v2-inference-v.yaml --H 768 --W 768
Traceback (most recent call last):
  File "scripts/txt2img.py", line 11, in <module>
    from pytorch_lightning import seed_everything
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/home/dl/.local/lib/python3.8/site-packages/pytorch_lightning/metrics/classification/accuracy.py", line 16, in <module>
    from torchmetrics import Accuracy as _Accuracy
  File "/home/dl/.local/lib/python3.8/site-packages/torchmetrics/__init__.py", line 43, in <module>
    from torchmetrics.detection import MAP  # noqa: E402
  File "/home/dl/.local/lib/python3.8/site-packages/torchmetrics/detection/__init__.py", line 14, in <module>
    from torchmetrics.detection.map import MAP  # noqa: F401
  File "/home/dl/.local/lib/python3.8/site-packages/torchmetrics/detection/map.py", line 35, in <module>
    from pycocotools.coco import COCO
  File "/home/dl/.local/lib/python3.8/site-packages/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/dl/.local/lib/python3.8/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "__init__.pxd", line 238, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject
```

**Comment by Dendiiip** [comment]
Uk
