### ISSUE TITLE
ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: (<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7F1D2C80>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD9A980>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD9BBB0>).

### ISSUE THREAD

**Issue by NiuDaVinci** [Stability-AI/stablediffusion#286]
2023-06-23 13:04:26,147 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: (<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7F1D2C80>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD9A980>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD9BBB0>).
2023-06-23 13:04:26,152 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: (<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7F1D2C80>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD9A980>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD9BBB0>).
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.90it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 15/15 [00:02<00:00,  5.83it/s]
2023-06-23 13:09:03,823 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: (<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD98C70>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD9BD00>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD99630>).
2023-06-23 13:09:03,824 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: (<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD98C70>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD9BD00>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x000001BE7BD99630>).

**Comment by kazuninishiki** [comment]
same.  Was doing tiles with ultimate upscaler.

2023-06-23 15:06:55,255 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: (<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000019AC0D3B160>,).
2023-06-23 15:06:55,257 - ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args passed to ControlNet: (<scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000019AC0D3B160>,).

**Comment by crankdawg47** [comment]
looks like it was an issue with the latest update. there's been a patch to the controlnet extension. updating it seems to have corrected error. Open pose isn't generating wireframe previews after img generation though. so not sure it's entirely fixed

**Comment by kazuninishiki** [comment]
Can confirm.  An update fixed it.

**Comment by hoodady** [comment]
how did you update it, when i go to my available extension everything seems to be updated

**Comment by alexmihaic** [comment]
I have the same problem here and I have updated everything

**Comment by syousip** [comment]
I have same issue with slightly different output in CLI:
![error](https://github.com/Stability-AI/stablediffusion/assets/121361502/ece023cf-d879-4ea2-ba32-7f39f7c93c80)

I have disabled all Extensions (Ext&Int) then restarted UI to see if it help, no luck either.

**Comment by enterv0id** [comment]
Any fix for this?

**Comment by Ainaemaet** [comment]
Same problem here as @syousip

**Comment by 93041025** [comment]
same issue for img2img. no problem with txt2img. i am not using any controlnet with img2img but warning generated. any update?

**Comment by kitamo1981** [comment]
I got that same - try to turn off move2move extension if U use it or other extensions and try to find that one witch conflict

**Comment by anx22** [comment]
Same problem, cant solve ;((
I reinstalled VENV Folder and deinstalled my last installed extensions. Controlnet stopped working

**Comment by fastjhone** [comment]
> I got that same - try to turn off move2move extension if U use it or other extensions and try to find that one witch conflict

its actually worked

**Comment by Flickarus** [comment]
> > I got that same - try to turn off move2move extension if U use it or other extensions and try to find that one witch conflict
> 
> its actually worked

That worked, thanks! but why has this conflict with mov2mov??

**Comment by willyzen6** [comment]
> I got that same - try to turn off move2move extension if U use it or other extensions and try to find that one witch conflict

yeah that works for me i hope mov2mov2 works again soon

**Comment by kitamo1981** [comment]
I 

> > > I got that same - try to turn off move2move extension if U use it or other extensions and try to find that one witch conflict
> > 
> > 
> > its actually worked
> 
> That worked, thanks! but why has this conflict with mov2mov??

its strange but i think that it have something to do with new version of Controlnet.  WIth older controlnet it works fine.
I think we need to wait for new version of controlnet or mov2mov.

**Comment by Whippetz** [comment]
I turned off SD-CN-Animation ext and it fixed it.

**Comment by Ho3einWave** [comment]
> I turned off SD-CN-Animation ext and it fixed it.

its worked for me thanks

**Comment by thedoger82** [comment]
i turn off sd-dynamic-prompts and then it started working with no errors

**Comment by aftermath0703** [comment]
I also got it working by disabling other plugins, but I don't think it's a wise thing to do because I had to disable 7 plugins to get it to work. However, in many cases many plugins are required to work together.
In addition, after I rolled back the stable diffusion for several versions, it can also be used normally

**Comment by plaeground** [comment]
having the same issue even after disabling almost every extension

**Comment by aftermath0703** [comment]
> having the same issue even after disabling almost every extension

you can also try reinstall these plugins, it also works for me

**Comment by JeanCrux** [comment]
Same proble here but I have no extension and it says "Here are args passed to ControlNet: ()... 
I have no window to put my image in img2img too, don't know if it's the same problem. 

Has anyone found a solution other than disabling extensions (I don't have any)?

**Comment by rodfdez** [comment]
Same problem, I disabled all the extensions, didn't work

**Comment by ybekocak** [comment]
Same here. On text2img and Img2img it's ok but on deforum, isn't working. Is there any solution?

**Comment by profinger** [comment]
Mine was doing this exact same thing but at some point (either during load or during run press maybe?) was throwing an error from the preset.py module.  
```
Error calling: H:\wusd\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
Traceback (most recent call last):
  File "H:\wusd\stable-diffusion-webui\modules\scripts.py", line 243, in wrap_call
    res = func(*args, **kwargs)
  File "H:\wusd\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 283, in ui
    group, state = self.uigroup(f"ControlNet", is_img2img, elem_id_tabname)
  File "H:\wusd\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 258, in uigroup
    group.register_callbacks(is_img2img)
  File "H:\wusd\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 825, in register_callbacks
    self.preset_panel.register_callbacks(
  File "H:\wusd\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\preset.py", line 177, in register_callbacks
    ).then(
AttributeError: 'dict' object has no attribute 'then'
```

as I have no need for presets and they seemed to have been implemented poorly, I just went and removed any reference to the preset stuff.  I can share what I did but it'll have to be later if someone is interested.

**Comment by rchennau** [comment]
@Whippetz thank you.  I had the same problem.   ControlNet - WARNING - No ControlNetUnit detected in args fails when the  SD-CN-Animation extension enabled.  (comment left for the internets to find)

**Comment by night2021-2021** [comment]
Same problem, but the error message do not contain anything.
`No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().`

**Comment by kino47** [comment]
In my case, the SD-CN-Animation extension https://github.com/volotat/SD-CN-Animation.git. It causes the conflict ( ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().)

**Comment by enochianborg** [comment]
set COMMANDLINE_ARGS= --update-check --update-all-extensions

**Comment by enochianborg** [comment]
> In my case, the SD-CN-Animation extension https://github.com/volotat/SD-CN-Animation.git. It causes the conflict ( ControlNet - WARNING - No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: ().)

I confirm this occured with my issue the same.  Unchecked SD-CN-Animation extension in extensions tab and APPLY / Restart.  The error went away.

**Comment by gittyoletime23** [comment]
Possibly same issue with SD-CN-Animation in Automatic1111. Causes ControlNet to be ignored or weird results.

**Comment by dengjianyue** [comment]
> I turned off SD-CN-Animation ext and it fixed it.

Yes,it works!!! Many thanks god
