### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Astraha** [Stability-AI/stablediffusion#319]
Error calling: D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 288, in ui
    group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname)
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 268, in uigroup
    group.register_callbacks(is_img2img)
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 820, in register_callbacks
    self.preset_panel.register_callbacks(
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\preset.py", line 177, in register_callbacks
    ).then(
AttributeError: 'dict' object has no attribute 'then'

Error calling: D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py/ui
Traceback (most recent call last):
  File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 262, in wrap_call
    res = func(*args, **kwargs)
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 288, in ui
    group, state = self.uigroup(f"ControlNet-{i}", is_img2img, elem_id_tabname)
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 268, in uigroup
    group.register_callbacks(is_img2img)
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 820, in register_callbacks
    self.preset_panel.register_callbacks(
  File "D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet_ui\preset.py", line 177, in register_callbacks
    ).then(
AttributeError: 'dict' object has no attribute 'then'

how can i fix it i got this after i updated my controlnet

**Comment by bhanuj10** [comment]
Hi @Astraha 

I suppose that this is your controlnet directory 

> D:\ai\stable-diffusion-webui\extensions\sd-webui-controlnet

Try deleting it and rerun the program if it runs then the problem is with the controlnet

Instead of updating try downloading the newest version and copy to the 'extensions' directory.
