### ISSUE TITLE
the error: print self.face_rec_model_path 

### ISSUE THREAD

**Issue by ShiguiLi** [Stability-AI/stablediffusion#325]
root@stablediffusion# python scripts/txt2img.py --prompt "a professional photograph of an astronaut riding a horse" --ckpt models/ldm/stable-diffusion-v1/model.ckpt  --config configs/stable-diffusion/v2-inference-v.yaml --H 768 --W 768 
Traceback (most recent call last):
  File "scripts/txt2img.py", line 16, in <module>
    from ldm.util import instantiate_from_config
  File "/root/miniconda3/lib/python3.8/site-packages/ldm.py", line 20
    print self.face_rec_model_path 
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

**Comment by bhanuj10** [comment]
Can you provide more details....

**Comment by Krikoset** [comment]
i have a app that create images and if i wanna 2:3 or diffiend and i wanna to do this that whear i input a prompt
