### ISSUE TITLE
windows xformers install breaking

### ISSUE THREAD

**Issue by heartlocket** [Stability-AI/stablediffusion#33]
hi, i am having issues installing xformers, breaking at pip install -e .

```
Obtaining file:///C:/Users/heart/Desktop/DEV/xformers
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\heart\Desktop\DEV\xformers\setup.py", line 270, in <module>
          ext_modules=get_extensions(),
        File "C:\Users\heart\Desktop\DEV\xformers\setup.py", line 210, in get_extensions
          cuda_version = get_cuda_version(CUDA_HOME)
        File "C:\Users\heart\Desktop\DEV\xformers\setup.py", line 67, in get_cuda_version
          raw_output = subprocess.check_output([nvcc_bin, "-V"], universal_newlines=True)
        File "C:\Users\heart\anaconda3\envs\stability\lib\subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\heart\anaconda3\envs\stability\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\heart\anaconda3\envs\stability\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\heart\anaconda3\envs\stability\lib\subprocess.py", line 1440, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by gmchim** [comment]
having the same issue. not the only one aswell. I've updated everything, downgraded everything and nothing seems to work,

**Comment by 0xdevalias** [comment]
Potentially related:

- https://github.com/Stability-AI/stablediffusion/issues/38

**Comment by 0xdevalias** [comment]
Are you following the xformers installatiomn instructions from here?

- https://github.com/facebookresearch/xformers#installing-xformers

> pip wheels: There is no updated package available on pip, please install from conda or from source

**Comment by Kepler-24** [comment]
I have met the similar error. However, I solved by installing Microsoft Visual C++ 14.0 or greater.
