### ISSUE TITLE
cant't clone at all

### ISSUE THREAD

**Issue by drc11** [Stability-AI/stablediffusion#333]
F:\stable diffusion\stable-diffusion-webui\repositories> Git clone https://github.com/Stability-AI/stablediffusion.git
Cloning into 'stablediffusion'...
remote: Enumerating objects: 577, done.
remote: Counting objects: 100% (307/307), done.
remote: Compressing objects: 100% (89/89), done.
error: RPC failed; curl 56 Failure when receiving data from the peer
error: 7491 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

**Comment by wfn53400** [comment]
the same question,

**Comment by wfn53400** [comment]
the same question！！！

Traceback (most recent call last):
  File "D:\Soft\stable-diffusion-webui\launch.py", line 48, in <module>
    main()
  File "D:\Soft\stable-diffusion-webui\launch.py", line 39, in main
    prepare_environment()
  File "D:\Soft\stable-diffusion-webui\modules\launch_utils.py", line 408, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "D:\Soft\stable-diffusion-webui\modules\launch_utils.py", line 192, in git_clone
    run(f'"{git}" clone "{url}" "{dir}"', f"Cloning {name} into {dir}...", f"Couldn't clone {name}", live=True)
  File "D:\Soft\stable-diffusion-webui\modules\launch_utils.py", line 116, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't clone Stable Diffusion.
Command: "git" clone "https://github.com/Stability-AI/stablediffusion.git" "D:\Soft\stable-diffusion-webui\repositories\stable-diffusion-stability-ai"
Error code: 128

**Comment by Halil1564** [comment]
did you fix that problem? I trouble with same :((

**Comment by blackmambaza** [comment]
git config http.postBuffer 524288000
