### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by wczdsg** [Stability-AI/stablediffusion#360]
Cloning Stable Diffusion into D:\software\app\stable-diffusion-webui-1.7.0\repositories\stable-diffusion-stability-ai...
Cloning into 'D:\software\app\stable-diffusion-webui-1.7.0\repositories\stable-diffusion-stability-ai'...
remote: Enumerating objects: 580, done.
remote: Counting objects: 100% (357/357), done.
remote: Compressing objects: 100% (126/126), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 139 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Traceback (most recent call last):
  File "D:\software\app\stable-diffusion-webui-1.7.0\launch.py", line 48, in <module>
    main()
  File "D:\software\app\stable-diffusion-webui-1.7.0\launch.py", line 39, in main
    prepare_environment()
  File "D:\software\app\stable-diffusion-webui-1.7.0\modules\launch_utils.py", line 408, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "D:\software\app\stable-diffusion-webui-1.7.0\modules\launch_utils.py", line 192, in git_clone
    run(f'"{git}" clone "{url}" "{dir}"', f"Cloning {name} into {dir}...", f"Couldn't clone {name}", live=True)
  File "D:\software\app\stable-diffusion-webui-1.7.0\modules\launch_utils.py", line 116, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't clone Stable Diffusion.
Command: "git" clone "https://github.com/Stability-AI/stablediffusion.git" "D:\software\app\stable-diffusion-webui-1.7.0\repositories\stable-diffusion-stability-ai"
Error code: 128

**Comment by blackmambaza** [comment]
Increase the buffer size to cater for slower network connections:

git config http.postBuffer 524288000

**Comment by maifeeulasad** [comment]
By taking @blackmambaza 's answer here is the solution which worked for me:
```
git clone -c http.postBuffer=524288000 https://github.com/Stability-AI/stablediffusion.git
```
