### ISSUE TITLE
image to depth

### ISSUE THREAD

**Issue by donewe** [Stability-AI/stablediffusion#415]
https://github.com/Stability-AI/stablediffusion?tab=readme-ov-file#depth-conditional-stable-diffusion

I am really beginner to this program and havent done any these coding? know really nothing about it.
https://www.youtube.com/watch?v=AjXQEXgHWGA&t=1018s

I was following it and all worked and at last script 

python scripts\gradio\depth2img.py configs\stable-diffusion\v2-midas-inference.yaml models\stable-diffusion\512-depth-ema.ckpt

it says and doesnt work. Can anyone give me some advice? I really need it soon so can't learn all these things. 

(ldm) c:\stablediffusion-main>python scripts\gradio\depth2img.py configs\stable-diffusion\v2-midas-inference.yaml models\stable-diffusion\512-depth-ema.ckpt
No module 'xformers'. Proceeding without it.
LatentDepth2ImageDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
C:\Users\user\anaconda3\envs\ldm\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
C:\Users\user\anaconda3\envs\ldm\lib\site-packages\timm\models\_factory.py:117: UserWarning: Mapping deprecated model name vit_base_resnet50_384 to current vit_base_r50_s16_384.orig_in21k_ft_in1k.
  model = create_fn(
C:\Users\user\anaconda3\envs\ldm\lib\site-packages\gradio\routes.py:1215: DeprecationWarning:
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

  @app.on_event("startup")
C:\Users\user\anaconda3\envs\ldm\lib\site-packages\fastapi\applications.py:4495: DeprecationWarning:
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

  return self.router.on_event(event_type)
C:\Users\user\anaconda3\envs\ldm\lib\site-packages\gradio\routes.py:1215: DeprecationWarning:
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

  @app.on_event("startup")
C:\Users\user\anaconda3\envs\ldm\lib\site-packages\fastapi\applications.py:4495: DeprecationWarning:
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).

  return self.router.on_event(event_type)
Traceback (most recent call last):
  File "scripts\gradio\depth2img.py", line 154, in <module>
    input_image = gr.Image(source='upload', type="pil")
  File "C:\Users\user\anaconda3\envs\ldm\lib\site-packages\gradio\component_meta.py", line 167, in wrapper
    return fn(self, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'source'

**Comment by james-hx-song** [comment]
I also have this issue. Can anyone respond to this? It looks like this line ```input_image = gr.Image(source='upload', type="pil")``` is causing the error.
